FROM node:22-alpine AS build

WORKDIR /app

COPY frontend/web-app/package*.json ./

RUN npm ci

COPY frontend/web-app ./

RUN npm run build


FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/web-app/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]